### ISSUE TITLE
Problem with checking bandwidth

### ISSUE THREAD

**Issue by dkondrat** [Red5/red5-server-common#52]
I ma trying to run `checkBandwidthUp` on my Red5 server. I've tried running on Java 1.7 and 1.8. I've tried running Red5 in versions 1.0.7 and 1.0.8. 

In both I am hitting the same problem. Might be something that I am doing wrong, but I am not sure what else could be wrong if not code. Basically when I am calling NetConnection I am not passing any parameters, but it says that I've passed `Double` and its trying to cast `Integer` out of it in line 65 of ClientServerDetection.java file. 

I have tried calling 

nc.call(_service, res, 1);

as well as 

var test:int = 1;
nc.call(_service, res, test);

Both result in the same error.

If I pass null it throw null exception error.

Would it be possible to update code in that line to parse Double into int? Or just parse whatever parameter [0] is into int?

Or help with telling me how to pass 1 second to the nc.call method.

Any help would be appreciated.

**This his how I am invoking the call:**

`oCS:ClientServerBandwidth  = new ClientServerBandwidth();
oCS.connection = oRTMPConn;
oCS.service = "checkBandwidthUp";
oCS.addEventListener(BandwidthDetectEvent.DETECT_COMPLETE,fUpCompleted);
oCS.addEventListener(BandwidthDetectEvent.DETECT_STATUS,fUpStatus);
oCS.addEventListener(BandwidthDetectEvent.DETECT_FAILED,fUpFailed);
oCS.start();
`

`public function start():void {
	nc.client = this;
	var obj:Array = new Array();
	nc.call(_service, res);
}`

**Here is the error I am getting:**

`[ERROR] [RTMPConnectionExecutor-4] org.red5.server.service.ServiceInvoker - Error executing call: Service: null Method: checkBandwidthUp Num Params: 1 0: 1.0
java.lang.reflect.InvocationTargetException: null
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.red5.server.service.ServiceInvoker.invoke(ServiceInvoker.java:192)
	at org.red5.server.service.ServiceInvoker.invoke(ServiceInvoker.java:114)
	at org.red5.server.net.rtmp.RTMPHandler.invokeCall(RTMPHandler.java:191)
	at org.red5.server.net.rtmp.RTMPHandler.onCommand(RTMPHandler.java:289)
	at org.red5.server.net.rtmp.BaseRTMPHandler.messageReceived(BaseRTMPHandler.java:116)
	at org.red5.server.net.rtmp.ReceivedMessageTask.call(ReceivedMessageTask.java:72)
	at org.red5.server.net.rtmp.ReceivedMessageTask.call(ReceivedMessageTask.java:38)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassCastException: java.lang.Double cannot be cast to java.lang.Integer
	at org.red5.server.stream.bandwidth.ClientServerDetection.checkBandwidth(ClientServerDetection.java:65)
	at org.red5.server.Client.checkBandwidthUp(Client.java:359)
	at org.red5.server.adapter.AbstractScopeAdapter.checkBandwidthUp(AbstractScopeAdapter.java:297)
	... 17 common frames omitted
`

**Comment by dkondrat** [comment]
Any help would be appreciated.

**Comment by wicm** [comment]
A quick solution would be to import the modified class from java/org/red5/server/stream/bandwidth/ClientServerDetection.java in your own project and enter this method into the file red5-web.xml.
  (<Bean id = "onClientBWCheck.service" class = "...)
This overwrites the default function.

**Comment by dkondrat** [comment]
@wicm Thank you for the tip. I will try to do that tomorrow and will see if that helps. I really appriciate the help.

**Comment by mondain** [comment]
I've patched this and it'll be in the next push
