### ISSUE TITLE
: Don't know how to handle message of type 'org.red5.server.net.rtmp.message.Packet'.  Are you missing a protocol encoder?

### ISSUE THREAD

**Issue by kaviyarasu1987** [Red5/red5-server-common#67]
occurs in android after we integrate through gradle library.Am not sure which place it occurs in RTMPMinaIoHandler since all libs coming from gradle please help thanks :)

**Comment by kaviyarasu1987** [comment]
Full exception here
 java.lang.IllegalStateException: Don't know how to handle message of type 'org.red5.server.net.rtmp.message.Packet'.  Are you missing a protocol encoder?
08-02 07:22:47.115 20262-20304/com.galwayfm.aaa.galwayfm I/System.out:     at org.apache.mina.core.polling.AbstractPollingIoProcessor$Processor.flushNow(AbstractPollingIoProcessor.java:1019)
08-02 07:22:47.115 20262-20304/com.galwayfm.aaa.galwayfm I/System.out:     at org.apache.mina.core.polling.AbstractPollingIoProcessor$Processor.flush(AbstractPollingIoProcessor.java:921)
08-02 07:22:47.115 20262-20304/com.galwayfm.aaa.galwayfm I/System.out:     at org.apache.mina.core.polling.AbstractPollingIoProcessor$Processor.run(AbstractPollingIoProcessor.java:688)
08-02 07:22:47.115 20262-20304/com.galwayfm.aaa.galwayfm I/System.out:     at org.apache.mina.util.NamePreservingRunnable.run(NamePreservingRunnable.java:64)
08-02 07:22:47.115 20262-20304/com.galwayfm.aaa.galwayfm I/System.out:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
08-02 07:22:47.115 20262-20304/com.galwayfm.aaa.galwayfm I/System.out:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
08-02 07:22:47.115 20262-20304/com.galwayfm.aaa.galwayfm I/System.out:     at java.lang.Thread.run(Thread.java:818)
